<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            markup: True
            font_size: 32
            text: "This is [size=150][color=#FF5733][b]bold[/b][/color][/size] text"

        Label:
            markup: True
            font_size: 32
            text: "This is [i]italic[/i] text"

        Button:
            markup: True
            font_size: 32
            text: "Click Me!"