<MyLayout>
    do_default_tab: False

    TabbedPanelItem:
        text: "Tab 1"
        Label:
            text: "Hello World"

    TabbedPanelItem:
        text: "Tab 2"
        BoxLayout:
            Label: 
                text: "Press the Button =>"
            Button:
                text: "Click me"

    TabbedPanelItem:
        text: "Tab 3"

        Image:
            source: "/home/narendra/Pictures/hanuman2.jpg"
            
